### ISSUE TITLE
RoslynQuoter doesn't handle case statements.

### ISSUE THREAD

**Issue by DRAirey1** [KirillOsenkov/RoslynQuoter#10]
Entering a simple case statement results in an error:

`class C
{
    public C()
    {
          int myValue = 2;
          switch(myValue)
          {
          case 1:
             break;
          }
    }
}`

`System.NotSupportedException: Specified method is not supported.
   at Quoter.AddModifyingCalls(Object treeElement, ApiCall apiCall, List values)
   at Quoter.QuoteNode(SyntaxNode node, String name)
`

**Comment by KirillOsenkov** [comment]
Fixed, thanks.

**Comment by DRAirey1** [comment]
Kirill,

                Confirmed.  Looks great.  Thanks.

 

Don Airey
