### ISSUE TITLE
Add support for parsing statements and expressions

### ISSUE THREAD

**Issue by svick** [KirillOsenkov/RoslynQuoter#11]
Currently, RoslynQuoter can only parse whole compilation units. If you want to see the code to generate a statement or an expression, you have to write it inside a method inside a class and then you need to figure out which part of the output do you actually need.

It would be nice if RoslynQuoter could support parsing statements and expressions directly.

Support for parsing methods would also be nice, but there doesn't seem to be a suitable `SyntaxFactory.Parse*` method for that.

**Comment by KirillOsenkov** [comment]
Merged and deployed, thanks!
