### ISSUE TITLE
Visual studio plugin

### ISSUE THREAD

**Issue by RikkiGibson** [KirillOsenkov/RoslynQuoter#14]
It would be amazing to have a visual studio plugin or Roslyn analyzer that offers a code fix which replaces a call to SyntaxFactory.Parse_ methods with a syntax tree literal. Is there any will to create this? I could try my hand at it at some point if that sounds appealing.

**Comment by KirillOsenkov** [comment]
I most certainly won't have time for this, but this shouldn't discourage enthusiastic contributors :)
