### ISSUE TITLE
C# 7 support

### ISSUE THREAD

**Issue by dudikeleti** [KirillOsenkov/RoslynQuoter#16]
Can you add please support to C# 7?

**Comment by KirillOsenkov** [comment]
Done, can you please try: http://roslynquoter.azurewebsites.net

It was harder than I expected.

**Comment by dudikeleti** [comment]
I've checked it for out variables, tuples, and patterns, and its looks great!
Thanks you!

> It was harder than I expected.

It was faster than I expected ;)
