### ISSUE TITLE
a bug in Quoter! (

### ISSUE THREAD

**Issue by MuradTulunay** [KirillOsenkov/RoslynQuoter#18]
Parse as statement 
 Open parenthesis on a new line 
 Closing parenthesis on a new line

private static bool isAuditInitialized = false;
        static void Instance_CustomizeAuditTrailSettings(object sender,
            CustomizeAuditTrailSettingsEventArgs e)
        {}

**Comment by KirillOsenkov** [comment]
This is actually a Roslyn bug:
https://github.com/dotnet/roslyn/issues/17458

Once Roslyn fixes the bug and I update to the latest Roslyn, the bug will be fixed.

For now for this code don't use Statement, use the global level parsing.

Thanks!

**Comment by MuradTulunay** [comment]
Kimden: Kirill Osenkov [mailto:notifications@github.com] 
Tarih: 28 Şubat 2017 Salı 22:23
Kime: KirillOsenkov/RoslynQuoter <RoslynQuoter@noreply.github.com>
Bilgi: MuradTulunay <murad.tulunay@gmail.com>; Author <author@noreply.github.com>
Konu: Re: [KirillOsenkov/RoslynQuoter] a bug in Quoter! ( (#18)

 

Closed #18 <https://github.com/KirillOsenkov/RoslynQuoter/issues/18> .
