### ISSUE TITLE
DOM XSS vulnerability in scripts.js in http://roslynquoter.azurewebsites.net/

### ISSUE THREAD

**Issue by guylando** [KirillOsenkov/RoslynQuoter#20]
The setResult function has the line:
container.innerHTML = data;
Where the data is the response from the server operating on the input value which I am pretty sure can be html.

**Comment by KirillOsenkov** [comment]
Thanks for logging this. Unfortunately I have no idea about this (beginner web dev). Do you have a fix in mind, or what are the potential implications of the attack?

**Comment by guylando** [comment]
Well .innerText instead of .innerHTML prevent the code from being executed so the question is if you really want the code be rendered as html and if so then maybe you can whitelist the tags you want to allow and then html encode all the string and string replace only the encoded whitelisted tags back to their unencoded form.

**Comment by guylando** [comment]
I now tested execution with 
<aaa"<h1>aa
and saw that the server encodes the response so the client side problem is dealt with by the server so I am closing this

**Comment by KirillOsenkov** [comment]
OK, cool, thanks for letting me know.
