### ISSUE TITLE
Getter property

### ISSUE THREAD

**Issue by brimfulofashar** [KirillOsenkov/RoslynQuoter#23]
public int a
{
get {return 100;}
}

System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.AddError[TNode](TNode node, ErrorCode code, Object[] args) at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ConsumeUnexpectedTokens[TNode](TNode node) at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseStatement(String text, Int32 offset, ParseOptions options, Boolean consumeFullText) at Quoter.Parse(String sourceText, NodeKind nodeKind) at QuoterService.Controllers.QuoterController.Get(String sourceText, NodeKind nodeKind, Boolean openCurlyOnNewLine, Boolean closeCurlyOnNewLine, Boolean preserveOriginalWhitespace, Boolean keepRedundantApiCalls, Boolean avoidUsingStatic)

**Comment by KirillOsenkov** [comment]
This is due to https://github.com/dotnet/roslyn/issues/17458

**Comment by KirillOsenkov** [comment]
Fixed.
