### ISSUE TITLE
add support for new xml parser

### ISSUE THREAD

**Issue by AviAvni** [KirillOsenkov/RoslynQuoter#3]
Please add support forhttps://github.com/KirillOsenkov/XmlParser

**Comment by KirillOsenkov** [comment]
You mean for a chunk of XML it should produce calls to syntax factory to produce that XML? Frankly I don't think this is as necessary as for C#, the tree structure is simple enough to figure it out, and when stuck you can always parse and inspect the tree in the debugger.

**Comment by AviAvni** [comment]
It's simple but can help sometime
I'll try do it my self base on your work
You have some advice?

**Comment by KirillOsenkov** [comment]
The source code is out there, good luck! :)

**Comment by KirillOsenkov** [comment]
Sorry I doubt I'll ever get to it.
