### ISSUE TITLE
Not working (NotSupportedException) with Microsoft.CodeAnalysis version 2.8.2 (on2.7. work)

### ISSUE THREAD

**Issue by neurosystemeu** [KirillOsenkov/RoslynQuoter#41]
When try :
`var quoter = new Quoter
            {
                OpenParenthesisOnNewLine = false,
                ClosingParenthesisOnNewLine = false,
                UseDefaultFormatting = !false,
                RemoveRedundantModifyingCalls = !false,
                ShortenCodeWithUsingStatic = !false
            };`

            `var t = quoter.Quote(@"this.Nowy.Funkcja(this.Ala * 2, 2)", NodeKind.Expression);`

The exception is thrown:
`throw new NotSupportedException("Sorry, this is a bug in Quoter. Please file a bug at https://github.com/KirillOsenkov/RoslynQuoter/issues/new.");`

The same code work ok with Microsoft.CodeAnalysis version 2.7.0

**Comment by KirillOsenkov** [comment]
Fixed with https://github.com/KirillOsenkov/RoslynQuoter/commit/3a7df64ccc4caf1a2b556fde1ab202798de50cb2 and deployed Roslyn 2.8.2 to the website.
