### ISSUE TITLE
Check syntax errors before generate the syntax tree?

### ISSUE THREAD

**Issue by Cyl18** [KirillOsenkov/RoslynQuoter#45]
![image](https://user-images.githubusercontent.com/14993992/54599391-8258d680-4a75-11e9-8520-1bf87ee41240.png)

**Comment by KirillOsenkov** [comment]
I’d say this is by design as sometimes you need to know how to generate trees to represent invalid programs.

Perhaps we could warn you if the tree has parse errors, but it should be apparent from all the missing and skipped tokens.
