### ISSUE TITLE
Codegen issue

### ISSUE THREAD

**Issue by jeauger-unity** [KirillOsenkov/RoslynQuoter#49]
I pasted the following code and observed a codegen issue.

```
if (coroutine.MoveNext())
  return;

Debug.Log("Cool");
```

**Comment by jeauger-unity** [comment]
I selected "Parse as Member" instead of "Statement".

**Comment by KirillOsenkov** [comment]
Thanks for the report. Still, it shouldn't crash. I've fixed the nullref so it now gives an error message instead of a crash call stack.
