### ISSUE TITLE
Equivalent for Expression Trees

### ISSUE THREAD

**Issue by rikimaru0345** [KirillOsenkov/RoslynQuoter#50]
Hey @KirillOsenkov, first of all RoslynQuoter is really useful, thank you for making it!

However I'm currently looking for a way to do the same for expression trees.
Basically taking c# source code and turning it into `Expression.*` calls.
Like an "Expression Tree Quoter" :smile: 

Google wasn't of any help and since you made *this* awesome tool, I figured I should just ask you  if you're aware of any way that could be done; or maybe a project that already does this. :smile:

**Comment by svick** [comment]
Have you tried decompiling the result of what the C# compiler does?

For example [here is the result of decompiling a simple `Expression`](https://sharplab.io/#v2:D4AQTAjAsAUCAMACEEB0AZAlgOwI6oFEAPABwCcBTAZyswHtsqBuWcRAYUQG9ZE/kIANkTFy1WgwA8IAKyScAFwA0iRQD41iCogC8q3ZsyJJiJAH5TiAFz6AVKpYwAvkA===), which shows you how to build it yourself using calls to methods on `Expression`.

**Comment by rikimaru0345** [comment]
Yes, but this isn't so much about getting it done at all (just to look at it), but rather about having an automated way (a library!) to do it.
Like a `string ConvertCSharpToExpressionCalls(string cSharpCode);`, hope that makes sense.

**Comment by svick** [comment]
Could you explain why you want that?

Generally, the output of a quoter is useful for a human, because they can then use it to write some other code.

But if you want a library, that usually means you want to process the output by a program. But what kind of program prefers e.g. `Expression.Lambda<Func<int>>(Expression.Constant(0, typeof(int)))` when `() => 0` can do the same thing?

**Comment by zspitz** [comment]
A little late to the party, but:

@rikimaru0345 I've written a [library](https://github.com/zspitz/ExpressionTreeToString) that [allows you to do this](https://github.com/zspitz/ExpressionTreeToString/wiki/Available-renderers#3-factory-methods), and a [Visual Studio visualizer](https://github.com/zspitz/ExpressionTreeVisualizer) that can expose the factory methods of a given expression tree while debugging.

@svick Being able to take the source code and convert it the compiler equivalent calls to factory methods is useful, but not always an option; specifically, when I don't have the source code of an expression tree, but only the runtime object.

**Comment by KirillOsenkov** [comment]
Wow @zspitz this is awesome!

**Comment by KirillOsenkov** [comment]
I'll close this issue as this seems to be a great solution:
https://github.com/KirillOsenkov/RoslynQuoter/issues/50#issuecomment-757342066

**Comment by davidfowl** [comment]
zomg
