### ISSUE TITLE
Web version of Roslyn Quoter has stopped working in IE

### ISSUE THREAD

**Issue by DarkBond** [KirillOsenkov/RoslynQuoter#6]
I was using it up until about 3 PM, 2/24.  Now I'm not getting any results back when I hit the 'submit' button.  Tried it on IE10, 9 using the default empty class.  Both versions failed to return values.

**Comment by KirillOsenkov** [comment]
Yup, it was intermittent whole day today as I've been figuring out how to redeploy the website. Try again now, it should be better.
