### ISSUE TITLE
[Question] What are requirements to analyzed code?

### ISSUE THREAD

**Issue by aensidhe** [KirillOsenkov/RoslynQuoter#7]
Hi.

I tried a couple of classes from our current generator (T4 template) and Quoter.exe build from last sources is crashing with long exception (log attached). I can give you sample code, but not in public isue tracker.

Thank you.
[Log.txt](https://github.com/KirillOsenkov/RoslynQuoter/files/147219/CodeToUse.txt)

**Comment by WillSullivan** [comment]
Look at the error-_The type or namespace name 'AttributeSingletonListSyntax' could not be found_

Your code referenced code that doesn't exist in the framework and is not included in what you pasted into the quoter.  How can the quoter handle that?

You can replace references with stubs in the pasted code and reverse engineer the result to include actual references.  

Basically, what you paste into the quoter must be able to compile without referencing anything not in the framework, or not provided in what you pasted.

**Comment by aensidhe** [comment]
Aha, much clearer now. Thank you very much.
