### ISSUE TITLE
`not` patterns incorrectly parsed

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/RoslynQuoter#71]
Parse `o is not null` as an expression, and you get:

```cs
IsPatternExpression(
    IdentifierName("o"),
    UnaryPattern(
        ConstantPattern(
            LiteralExpression(
                SyntaxKind.NullLiteralExpression))))
.NormalizeWhitespace()
```

Note that the `not` in the expression is nowhere represented.

**Comment by KirillOsenkov** [comment]
This appears to be correct: the UnaryPattern only allows NotKeyword:
https://github.com/dotnet/roslyn/blob/badcd003f616de451aa1ce04191f27c0be835c4d/src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs#L3720

If you check `Keep redundant API calls` it will show the NotKeyword:
![image](https://user-images.githubusercontent.com/679326/130524349-10de3055-d777-4718-a5ee-13f1767ac272.png)

Quoter has detected that setting it explicitly is redundant and has eliminated it.

P.S. I'm not quite sure why the syntax tree shown by SharpLab looks like this though:
![image](https://user-images.githubusercontent.com/679326/130524595-3978da2c-85dd-48c7-a31d-0f798a971c58.png)

Maybe @ashmind knows?

When I parse myself and look at the syntax tree, it looks just like what Quoter does:
![image](https://user-images.githubusercontent.com/679326/130524792-c663e511-3a9f-4d4d-a306-2c58e9ae3df4.png)

**Comment by AArnott** [comment]
When I use the code the quoter gives me, no `not` keyword appears in the generated C# code.

This is what I had to use to actually get `not` to show up: https://github.com/AArnott/CSharpIsNull/blob/09d8a209b3e150cc79ba4eeaf2dedd69a6a76999/src/CSharpIsNullAnalyzer.CodeFixes/CSIsNull002Fixer.cs#L36

**Comment by AArnott** [comment]
Ok, never mind. It works. I guess I had some other bug at the time when it appeared to not work.
