### ISSUE TITLE
Null character syntax generated is faulty

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/RoslynQuoter#72]
Given this "statement":
```cs
char ch = '\0';
```

The generated code is:
```cs
LiteralExpression(SyntaxKind.CharacterLiteralExpression, Literal(''))
```

Note the *empty` character literal, which the C# compiler emits error CS1011 for.
I believe it *should* be 
```cs
LiteralExpression(SyntaxKind.CharacterLiteralExpression, Literal('\0'))
```

**Comment by KirillOsenkov** [comment]
Fixed and deployed, thanks for reporting.
